apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spodial-hr.fullname" . }}-application-migration-{{ .Release.Revision }}
  labels:
    {{- include "spodial-hr.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.migration.backoffLimit }}
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ include "spodial-hr.fullname" . }}-application-pull-secret
      containers:
      - name: migration
        args: ["migration"]
        image: "{{ .Values.application.image.registry }}/{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
        imagePullPolicy: {{ .Values.application.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "spodial-hr.fullname" . }}-application-envs
