apiVersion: v1
kind: Service
metadata:
  name: {{ include "spodial-hr-backend.fullname" . }}-application
  labels:
    {{- include "spodial-hr-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: nginx-http
      protocol: TCP
      name: http
  selector:
    {{- include "spodial-hr-backend.selectorLabels" . | nindent 4 }}
