apiVersion: v1
kind: Service
metadata:
  name: {{ include "spodial-hr.fullname" . }}-application
  labels:
    {{- include "spodial-hr.labels" . | nindent 4 }}-application
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: nginx-http
      protocol: TCP
      name: http
  selector:
    {{- include "spodial-hr.selectorLabels" . | nindent 4 }}-application
