apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spodial-hr.fullname" . }}-application-pull-secret
  labels:
    {{- include "spodial-hr.labels" . | nindent 4 }}-application-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "spodial-hr.imagePullSecret" .Values.application.image }}