apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spodial-hr-backend.fullname" . }}-application-pull-secret
  labels:
    {{- include "spodial-hr-backend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "spodial-hr-backend.imagePullSecret" .Values.application.image }}