apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spodial-hr-backend.fullname" . }}-application-nginx-config
  labels:
    {{- include "spodial-hr-backend.labels" . | nindent 4 }}
data:
  application-nginx-config.conf: |-
    {{ .Files.Get "files/nginx.conf" | nindent 4 }}