#!/bin/sh
set -e;

command="$1"

case "$command" in
  "backend" )
    php-fpm -R
  ;;
  "migration" )
    php artisan migrate
  ;;
  "nginx" )
    ln -sf /dev/stdout /var/log/nginx/access.log  
    ln -sf /dev/stdout /var/log/nginx/access.log    
    nginx -g "daemon off;"
  ;;
  * )
    exec "$@"
  ;;  
esac
