<?php

namespace App\Services\ExtractionPlan;

use App\Enums\FollowupStatus;
use App\Events\MeetingReviewGenerated;
use App\Exceptions\AppException;
use App\Jobs\ExtractEpicsFromTranscriptJob;
use App\Models\CalendarEvent;
use App\Models\ExtractionPlan;
use App\Models\Team;
use App\Models\TaskDataUpload;
use App\Models\TranscriptUpload;
use App\Models\User;
use App\Services\Decisions\ExtractDecisionsService;
use App\Services\Extraction\ExtractionPlanSections;
use App\Services\Issue\IssueExtractionFanout;
use App\Services\Issue\TaskDataUploadSourceContext;
use App\Services\IssueMergeService;
use App\Services\TaskData\TaskDataFanout;
use Illuminate\Bus\UniqueLock;
use Illuminate\Contracts\Cache\Repository as CacheRepository;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Commits an approved ExtractionPlan and replays the exact downstream the original jobs run today.
 *
 * Lifecycle: guard + WRITE (applyPlan issues/decisions) + flip status → all in ONE transaction, so a
 * failure rolls everything back and the plan stays re-approvable (never stranded 'approved' with
 * nothing written). The REPLAY (job dispatch, Telegram, upload-status) runs AFTER commit through the
 * shared fanout seams, so the gated path produces the identical jobs/events as the flag-off path —
 * no drift. Gap-fill issues + epics are generated by the replayed VerifyMeetingArtifactsJob
 * (deliberately NOT moderated — see PREMODERATION_PLAN.md §1).
 */
class ApproveExtractionPlanService
{
    /** Human approve: guard + apply + flip atomically, then replay downstream after commit. */
    public function approve(ExtractionPlan $plan): array
    {
        $ctx = DB::transaction(function () use ($plan) {
            $locked = ExtractionPlan::whereKey($plan->id)->lockForUpdate()->first();
            if (! $locked || ! $locked->isPendingReview()) {
                return null; // double-approve / not reviewable — block (idempotent)
            }

            return $this->applyAndFlip($locked);
        });

        if ($ctx === null) {
            throw new AppException('Plan is not awaiting review', 'PLAN_NOT_PENDING', 409);
        }

        $this->replay($ctx);

        return $ctx['counts'];
    }

    /**
     * Zero-content auto-finish: the coordinator already flipped a 0-issue/0-decision plan to
     * 'approved' (no human). Apply (nothing) + replay downstream so the upload still reaches 'done',
     * exactly as the flag-off skip does. Runs exactly once (guarded by reviewed_at).
     */
    public function finalizeAutoApproved(ExtractionPlan $plan): void
    {
        $ctx = DB::transaction(function () use ($plan) {
            $locked = ExtractionPlan::whereKey($plan->id)->lockForUpdate()->first();
            if (! $locked || ! $locked->isApproved() || $locked->reviewed_at !== null) {
                return null;
            }

            return $this->applyAndFlip($locked);
        });

        if ($ctx !== null) {
            $this->replay($ctx);
        }
    }

    /**
     * Writes issues + decisions AND flips the plan to approved, all inside the CALLER's transaction
     * (the inner applyPlan / applyDecisionPlan transactions become savepoints). A failure here rolls
     * back the whole approve — no half-applied rows, no stranded-approved plan. Returns the context
     * the post-commit replay needs. Performs NO job dispatch / external calls.
     *
     * @return array{type: string, counts: array<string, int>}
     */
    private function applyAndFlip(ExtractionPlan $plan): array
    {
        $ctx = $plan->sourceable_type === TaskDataUpload::class
            ? $this->applyTaskData($plan)
            : $this->applyTranscript($plan);

        $plan->forceFill([
            'status'      => ExtractionPlan::STATUS_APPROVED,
            'reviewed_at' => $plan->reviewed_at ?? now(),
        ])->save();

        return $ctx;
    }

    /** WRITES only (runs inside the approve transaction). */
    private function applyTranscript(ExtractionPlan $plan): array
    {
        $event = CalendarEvent::find($plan->sourceable_id);
        if (! $event) {
            return ['type' => 'transcript', 'event' => null, 'counts' => $this->zeroCounts()];
        }

        $planData = $plan->plan ?? [];
        $issuesSection = $planData['issues'] ?? null;
        $decisionsSection = $planData['decisions'] ?? null;

        $issues = collect();
        $team = null;
        $user = null;

        if (is_array($issuesSection) && ! empty($issuesSection['items'])) {
            $team = Team::find($issuesSection['team_id'] ?? $plan->team_id);
            $user = User::find($issuesSection['user_id'] ?? $plan->user_id);

            if ($team && $user) {
                $computePlan = $this->guardStaleUpdates(
                    ExtractionPlanSections::toComputePlan($issuesSection),
                    $issuesSection['existing_snapshots'] ?? [],
                );
                $issues = app(IssueMergeService::class)->applyPlan($computePlan, $event, $team, $user);
            }
        }

        $decisionsCreated = 0;
        $summary = $event->meetingSummary()->first();
        if ($summary && is_array($decisionsSection['items'] ?? null) && $decisionsSection['items'] !== []) {
            $decisionsCreated = app(ExtractDecisionsService::class)->applyDecisionPlan($summary, $decisionsSection['items']);
        }

        // Fall back to the plan's resolved team/user when there were no issue items (decisions-only /
        // empty plan) so the downstream replay still has the meeting's team context.
        $team ??= Team::find($plan->team_id);
        $user ??= User::find($plan->user_id);

        return [
            'type'   => 'transcript',
            'event'  => $event,
            'team'   => $team,
            'user'   => $user,
            'issues' => $issues,
            'counts' => [
                'issues_created'    => $issues->count(),
                'issues_updated'    => 0,
                'decisions_created' => $decisionsCreated,
            ],
        ];
    }

    /** WRITES only (runs inside the approve transaction). */
    private function applyTaskData(ExtractionPlan $plan): array
    {
        $upload = TaskDataUpload::find($plan->sourceable_id);
        if (! $upload) {
            return ['type' => 'task_data', 'upload' => null, 'counts' => $this->zeroCounts()];
        }

        $team = Team::find($upload->team_id);
        $user = User::find($upload->user_id);
        $issuesSection = ($plan->plan ?? [])['issues'] ?? null;

        $created = collect();
        $updated = collect();

        if ($team && $user && is_array($issuesSection) && ! empty($issuesSection['items'])) {
            $ctx = new TaskDataUploadSourceContext($upload);
            $computePlan = $this->guardStaleUpdates(
                ExtractionPlanSections::toComputePlan($issuesSection),
                $issuesSection['existing_snapshots'] ?? [],
            );
            $result = app(IssueMergeService::class)->applyPlanFromSource($computePlan, $team, $user, $ctx);
            $created = $result['created'];
            $updated = $result['updated'];
        }

        return [
            'type'    => 'task_data',
            'upload'  => $upload,
            'team'    => $team,
            'user'    => $user,
            'created' => $created,
            'updated' => $updated,
            'counts'  => [
                'issues_created'    => $created->count(),
                'issues_updated'    => $updated->count(),
                'decisions_created' => 0,
            ],
        ];
    }

    /**
     * Dispatch downstream + Telegram + upload-status, AFTER the apply transaction has committed.
     * Mirrors the flag-off jobs' tails exactly (shared fanout seams), so no drift.
     */
    private function replay(array $ctx): void
    {
        if ($ctx['type'] === 'transcript') {
            $event = $ctx['event'];
            if (! $event) {
                return;
            }
            $team = $ctx['team'];
            $user = $ctx['user'];

            // Release the epic job's unique lock first so a re-upload/re-approve within the hour is
            // not silently suppressed.
            if ($team && $user) {
                $this->releaseEpicLock($event, $team, $user);
                app(IssueExtractionFanout::class)->afterIssues($ctx['issues'], $event, $team, $user);
            }

            // Deferred meeting-review notification.
            $review = $event->meetingReview()->first();
            if ($review && $review->status !== FollowupStatus::FAILED->value) {
                MeetingReviewGenerated::dispatch($review->fresh());
            }

            TranscriptUpload::where('calendar_event_id', $event->id)
                ->whereNotIn('status', ['failed'])
                ->update(['status' => 'done']);

            Log::info('extraction_plan.transcript.approved', [
                'plan_id'           => $event->id,
                'calendar_event_id' => $event->id,
                'issues'            => $ctx['counts']['issues_created'],
                'decisions'         => $ctx['counts']['decisions_created'],
            ]);

            return;
        }

        $upload = $ctx['upload'];
        if (! $upload) {
            return;
        }
        $team = $ctx['team'];
        $user = $ctx['user'];

        if ($team && $user) {
            app(TaskDataFanout::class)->afterIssues($upload, $user, $ctx['created'], $ctx['updated']);
        } else {
            $upload->update(['status' => 'done', 'issues_created' => 0, 'issues_updated' => 0, 'updated_issue_ids' => []]);
        }

        Log::info('extraction_plan.task_data.approved', [
            'upload_id' => $upload->id,
            'created'   => $ctx['counts']['issues_created'],
            'updated'   => $ctx['counts']['issues_updated'],
        ]);
    }

    /** @return array<string, int> */
    private function zeroCounts(): array
    {
        return ['issues_created' => 0, 'issues_updated' => 0, 'decisions_created' => 0];
    }

    /**
     * Optimistic-concurrency: if an existing issue targeted by an UPDATE decision was mutated since
     * compute (live updated_at != snapshot), demote that decision to 'skip' so we never clobber a
     * concurrently-edited row. Lives here (the moderated path) — the shared applyDecisions* is untouched.
     */
    private function guardStaleUpdates(array $computePlan, array $snapshots): array
    {
        $decisions = $computePlan['decisions'] ?? null;
        if (! is_array($decisions) || $decisions === []) {
            return $computePlan;
        }

        $snapshotUpdatedAt = [];
        foreach ($snapshots as $snap) {
            if (isset($snap['id'])) {
                $snapshotUpdatedAt[(int) $snap['id']] = $snap['updated_at'] ?? null;
            }
        }

        $liveUpdatedAt = [];
        $ids = collect($decisions)
            ->filter(fn ($d) => ($d['action'] ?? null) === 'update' && ! empty($d['existing_issue_id']))
            ->pluck('existing_issue_id')
            ->unique()
            ->all();
        if ($ids !== []) {
            $liveUpdatedAt = \App\Models\Issue::whereIn('id', $ids)
                ->pluck('updated_at', 'id')
                ->map(fn ($ts) => $ts?->toIso8601String())
                ->all();
        }

        foreach ($decisions as $i => $decision) {
            if (($decision['action'] ?? null) !== 'update' || empty($decision['existing_issue_id'])) {
                continue;
            }
            $id = (int) $decision['existing_issue_id'];
            $snap = $snapshotUpdatedAt[$id] ?? null;
            $live = $liveUpdatedAt[$id] ?? null;
            if ($snap !== null && $live !== null && $snap !== $live) {
                $decisions[$i]['action'] = 'skip';
                Log::info('extraction_plan.stale_update_skipped', ['issue_id' => $id]);
            }
        }

        $computePlan['decisions'] = $decisions;

        return $computePlan;
    }

    private function releaseEpicLock(CalendarEvent $event, Team $team, User $user): void
    {
        try {
            (new UniqueLock(app(CacheRepository::class)))
                ->release(new ExtractEpicsFromTranscriptJob($event, $team, $user));
        } catch (\Throwable $e) {
            Log::warning('extraction_plan.epic_unlock_failed', ['event_id' => $event->id, 'error' => $e->getMessage()]);
        }
    }
}
