application:
  image:
    registry: registry.fabit.ru
    repository: tribes/tribes
    tag: latest
    pullPolicy: IfNotPresent
    credentials:
      username: username
      password: password
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  livenessProbe: {}
  readinessProbe: {}
  config:
    frontendUrl: "frontendUrl"
    appName: "appName"
    appKey: "appKey"
    appEnv: "appEnv"
    appDebug: "appDebug"
    appUrl: "appUrl"
    appLocale: "appLocale"
    appFallbackLocale: "appFallbackLocale"
    appFakerLocale: "appFakerLocale"
    appMaintenanceDriver: "appMaintenanceDriver"
    phpCliServerWorkers: "phpCliServerWorkers"
    bcryptRounds: "bcryptRounds"
    logChannel: "logChannel"
    logStack: "logStack"
    logDeprecationsChannel: "logDeprecationsChannel"
    logLevel: "logLevel"
    dbConnection: "dbConnection"
    dbHost: "dbHost"
    dbPort: "dbPort"
    dbDatabase: "dbDatabase"
    dbUsername: "dbUsername"
    dbPassword: "dbPassword"
    sessionDriver: "sessionDriver"
    sessionLifetime: "sessionLifetime"
    sessionEncrypt: "sessionEncrypt"
    sessionPath: "sessionPath"
    sessionDomain: "sessionDomain"
    broadcastConnection: "broadcastConnection"
    filesystemDisk: "filesystemDisk"
    queueConnection: "queueConnection"
    cacheStore: "cacheStore"
    memcachedHost: "memcachedHost"
    redisClient: "redisClient"
    redisHost: "redisHost"
    redisPassword: "redisPassword"
    redisPort: "redisPort"
    mailMailer: "mailMailer"
    mailScheme: "mailScheme"
    mailHost: "mailHost"
    mailPort: "mailPort"
    mailUsername: "mailUsername"
    mailPassword: "mailPassword"
    mailFromAddress: "mailFromAddress"
    mailFromName: "mailFromName"
    awsAccessKeyId: "awsAccessKeyId"
    awsSecretAccessKey: "awsSecretAccessKey"
    awsDefaultRegion: "awsDefaultRegion"
    awsBucket: "awsBucket"
    awsUsePathStyleEndpoint: "awsUsePathStyleEndpoint"
    viteAppName: "viteAppName"
    googleClientId: "googleClientId"
    googleClientSecret: "googleClientSecret"
    recallApiToken: "recallApiToken"    
    proxyHost: "ProxyHost"
    proxyPort: "ProxyPort"
    proxyUser: "ProxyUser"
    proxyPass: "ProxyPass"
    openrouterApiToken: "OpenrouterApiToken"

migration:
  activeDeadlineSeconds: 7200
  backoffLimit: 5
nginx:
  image:
    registry: third-party-registry.fabit.ru
    repository: docker.io/library/nginx
    tag: 1.27.5-alpine3.21-slim
    pullPolicy: IfNotPresent
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # livenessProbe:
  #   initialDelaySeconds: 30
  #   periodSeconds: 3
  #   timeoutSeconds: 5
  #   failureThreshold: 6
  #   successThreshold: 3    
  #   httpGet:
  #     path: /
  #     port: nginx-http
  # readinessProbe:
  #   initialDelaySeconds: 30
  #   periodSeconds: 3
  #   timeoutSeconds: 5
  #   failureThreshold: 6
  #   successThreshold: 3    
  #   httpGet:
  #     path: /
  #     port: nginx-http   
  service:
    type: ClusterIP
    port: 80
    